# 1. Son Ubuntu versiyası əsasında image yaradılır
FROM ubuntu:latest

# 2. Sistemin yenilənməsi
RUN apt-get update && apt-get upgrade -y

# 3. Kontainer işə düşəndə “Hello, World!” mesajı verəcək
CMD echo "Hello, World!"
